export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const BOOK_LOADED = "BOOK_LOADED";
export const BOOKS_SEARCHED = "BOOKS_SEARCHED";
export const BOOK_SEARCH_ERROR = "BOOK_SEARCH_ERROR";
export const REVIEW_POSTED = "REVIEW_POSTED";
export const REVIEW_POST_ERROR = "REVIEW_POST_ERROR";
export const BOOK_LOAD_ERROR = "BOOK_LOAD_ERROR";
export const SCORE_UPDATED = "SCORE_UPDATED";
export const SCORE_UPDATE_ERROR = "SCORE_UPDATE_ERROR";

export const SET_TEMP_INFO = "SET_TEMP_INFO";

